name: theloanapp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.6
  googleapis_auth: ^1.4.1
  dialog_flowtter: ^0.3.2
  rxdart: ^0.28.0
  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.6.8
  firebase_core: ^3.13.1
  firebase_database: ^11.3.6
  go_router: ^15.1.3
  flutter_riverpod: ^2.6.1
  firebase_core_web: ^2.0.0
  flutter_web3: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_auth: ^5.5.4
  flutter_screenutil: ^5.9.0
  google_fonts: ^4.0.4
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/loanassistbot.json
    - assets/loan_request.png
    - assets/electronics.jpg
    - assets/illustration.png
    - assets/apparel.jpg
    - assets/beauty.jpg
    - assets/car_store.png
    - assets/first.jpg
    - assets/second.jpg
    - assets/third.webp
    - assets/fourth.webp
    - assets/home.jpg
    - assets/illustration.jpg
    - assets/img10.jpeg
    - assets/img20.jpeg
    - assets/img30.jpeg
    - assets/img40.jpeg
    - assets/img50.jpeg
    - assets/leaves.png
    - assets/logo.png
    - assets/logo.jpg
    - assets/logo_banner.png
    - assets/start_screen.png
    - assets/pen_paper.png
    - assets/coin_stack.png
    - assets/sofa_sitting.png
